--[[---------------------------------------------------------------------------
Door groups
---------------------------------------------------------------------------
The server owner can set certain doors as owned by a group of people, identified by their jobs.


HOW TO MAKE A DOOR GROUP:
AddDoorGroup("NAME OF THE GROUP HERE, you will see this when looking at a door", Team1, Team2, team3, team4, etc.)
---------------------------------------------------------------------------]]


-- Example: AddDoorGroup("Cops and Mayor only", TEAM_CHIEF, TEAM_POLICE, TEAM_MAYOR)
-- Example: AddDoorGroup("Gundealer only", TEAM_GUN)

AddDoorGroup("5th Fleet Security", TEAM_5THFLEETTROOPER, TEAM_5THFLEETMEDIC, TEAM_5THFLEETHEAVY, TEAM_5THFLEETNCO, TEAM_5THFLEETOFFICER, TEAM_5THFLEETCOMMANDER)
AddDoorGroup("Naval Personnel Only", TEAM_CREWMAN, TEAM_VIXENSQUADRONPILOT, TEAM_VIXENSQUADRONCOMMANDER, TEAM_NAVALOFFICER, TEAM_DIRECTOROFOPERATIONS, TEAM_CAPTAINOFTHESHIP)
AddDoorGroup("Officer+", TEAM_CLONEOFFICER, TEAM_501STOFFICER, TEAM_501STCOMMANDER, TEAM_187THOFFICER, TEAM_187THCOMMANDER, TEAM_91STOFFICER, TEAM_91STCOMMANDER, TEAM_5THFLEETOFFICER, TEAM_5THFLEETCOMMANDER, TEAM_NAVALOFFICER, TEAM_DIRECTOROFOPERATIONS, TEAM_CAPTAINOFTHESHIP, TEAM_MARSHALCOMMANDER, TEAM_VIXENSQUADRONCOMMANDER, TEAM_VIXENSQUADRONPILOT)
AddDoorGroup("5th Fleet & Naval Personnel", TEAM_CREWMAN, TEAM_VIXENSQUADRONPILOT, TEAM_VIXENSQUADRONCOMMANDER, TEAM_NAVALOFFICER, TEAM_DIRECTOROFOPERATIONS, TEAM_CAPTAINOFTHESHIP, TEAM_5THFLEETTROOPER, TEAM_5THFLEETMEDIC, TEAM_5THFLEETHEAVY, TEAM_5THFLEETNCO, TEAM_5THFLEETOFFICER, TEAM_5THFLEETCOMMANDER)